import { PrismaClient, Prisma } from "@prisma/client";

const prisma = new PrismaClient();

const userData: Prisma.UserCreateInput[] = [
  {
    givenNames: "John",
    familyNames: "Doe 1",
    docIdNumber: 123456,
    signatureFileUrl: "-",
    photoFileUrl: "-",
    countryCode: "CO",
    state: "Bogotá D.C.",
    city: "Bogotá D.C.",
    fingerprintFileUrl: "-",
    birthDate: new Date(1996, 10, 30),
    height: 180,
    bloodType: "O",
    rh: "Positive",
    gender: "Male",
    expeditionDate: new Date(),
    expeditionPlace: "Some place",
    createdDatetime: new Date(),
    updatedDatetime: new Date(),
  },
  {
    givenNames: "John",
    familyNames: "Doe 2",
    docIdNumber: 234567,
    signatureFileUrl: "-",
    photoFileUrl: "-",
    countryCode: "CO",
    state: "Bogotá D.C.",
    city: "Bogotá D.C.",
    fingerprintFileUrl: "-",
    birthDate: new Date(1996, 10, 30),
    height: 180,
    bloodType: "O",
    rh: "Positive",
    gender: "Male",
    expeditionDate: new Date(),
    expeditionPlace: "Some place",
    createdDatetime: new Date(),
    updatedDatetime: new Date(),
  },
  {
    givenNames: "John",
    familyNames: "Doe 3",
    docIdNumber: 345678,
    signatureFileUrl: "-",
    photoFileUrl: "-",
    countryCode: "CO",
    state: "Bogotá D.C.",
    city: "Bogotá D.C.",
    fingerprintFileUrl: "-",
    birthDate: new Date(1996, 10, 30),
    height: 180,
    bloodType: "O",
    rh: "Positive",
    gender: "Male",
    expeditionDate: new Date(),
    expeditionPlace: "Some place",
    createdDatetime: new Date(),
    updatedDatetime: new Date(),
  },
  {
    givenNames: "John",
    familyNames: "Doe 4",
    docIdNumber: 456789,
    signatureFileUrl: "-",
    photoFileUrl: "-",
    countryCode: "CO",
    state: "Bogotá D.C.",
    city: "Bogotá D.C.",
    fingerprintFileUrl: "-",
    birthDate: new Date(1996, 10, 30),
    height: 180,
    bloodType: "O",
    rh: "Positive",
    gender: "Male",
    expeditionDate: new Date(),
    expeditionPlace: "Some place",
    createdDatetime: new Date(),
    updatedDatetime: new Date(),
  },
  {
    givenNames: "John",
    familyNames: "Doe 5",
    docIdNumber: 567890,
    signatureFileUrl: "-",
    photoFileUrl: "-",
    countryCode: "CO",
    state: "Bogotá D.C.",
    city: "Bogotá D.C.",
    fingerprintFileUrl: "-",
    birthDate: new Date(1996, 10, 30),
    height: 180,
    bloodType: "O",
    rh: "Positive",
    gender: "Male",
    expeditionDate: new Date(),
    expeditionPlace: "Some place",
    createdDatetime: new Date(),
    updatedDatetime: new Date(),
  },
  {
    givenNames: "Mary",
    familyNames: "Sue 1",
    docIdNumber: 678901,
    signatureFileUrl: "-",
    photoFileUrl: "-",
    countryCode: "CO",
    state: "Bogotá D.C.",
    city: "Bogotá D.C.",
    fingerprintFileUrl: "-",
    birthDate: new Date(1996, 10, 30),
    height: 180,
    bloodType: "O",
    rh: "Positive",
    gender: "Male",
    expeditionDate: new Date(),
    expeditionPlace: "Some place",
    createdDatetime: new Date(),
    updatedDatetime: new Date(),
  },
  {
    givenNames: "Mary",
    familyNames: "Sue 2",
    docIdNumber: 789012,
    signatureFileUrl: "-",
    photoFileUrl: "-",
    countryCode: "CO",
    state: "Bogotá D.C.",
    city: "Bogotá D.C.",
    fingerprintFileUrl: "-",
    birthDate: new Date(1996, 10, 30),
    height: 180,
    bloodType: "O",
    rh: "Positive",
    gender: "Male",
    expeditionDate: new Date(),
    expeditionPlace: "Some place",
    createdDatetime: new Date(),
    updatedDatetime: new Date(),
  },
  {
    givenNames: "Mary",
    familyNames: "Sue 3",
    docIdNumber: 890123,
    signatureFileUrl: "-",
    photoFileUrl: "-",
    countryCode: "CO",
    state: "Bogotá D.C.",
    city: "Bogotá D.C.",
    fingerprintFileUrl: "-",
    birthDate: new Date(1996, 10, 30),
    height: 180,
    bloodType: "O",
    rh: "Positive",
    gender: "Male",
    expeditionDate: new Date(),
    expeditionPlace: "Some place",
    createdDatetime: new Date(),
    updatedDatetime: new Date(),
  },
  {
    givenNames: "Mary",
    familyNames: "Sue 4",
    docIdNumber: 901234,
    signatureFileUrl: "-",
    photoFileUrl: "-",
    countryCode: "CO",
    state: "Bogotá D.C.",
    city: "Bogotá D.C.",
    fingerprintFileUrl: "-",
    birthDate: new Date(1996, 10, 30),
    height: 180,
    bloodType: "O",
    rh: "Positive",
    gender: "Male",
    expeditionDate: new Date(),
    expeditionPlace: "Some place",
    createdDatetime: new Date(),
    updatedDatetime: new Date(),
  },
  {
    givenNames: "Mary",
    familyNames: "Sue 5",
    docIdNumber: 987654,
    signatureFileUrl: "-",
    photoFileUrl: "-",
    countryCode: "CO",
    state: "Bogotá D.C.",
    city: "Bogotá D.C.",
    fingerprintFileUrl: "-",
    birthDate: new Date(1996, 10, 30),
    height: 180,
    bloodType: "O",
    rh: "Positive",
    gender: "Male",
    expeditionDate: new Date(),
    expeditionPlace: "Some place",
    createdDatetime: new Date(),
    updatedDatetime: new Date(),
  },
];

async function main() {
  console.log(`Start seeding ...`);
  for (const u of userData) {
    const user = await prisma.user.create({
      data: u,
    });
    console.log(`Created user with id: ${user.id}`);
  }
  console.log(`Seeding finished.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
