version: '3.8'
services:
  db:
    image: mysql
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - backend
  backend:
    depends_on:
      - db
    build: ./backend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - NODE_LOCAL_PORT=$NODE_LOCAL_PORT
      - MYSQLDB_HOST=$MYSQLDB_HOST
      - MYSQLDB_USER=$MYSQLDB_USER
      - MYSQLDB_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQLDB_DATABASE=$MYSQLDB_DATABASE
      - MYSQLDB_LOCAL_PORT=$MYSQLDB_LOCAL_PORT
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
    networks:
      - backend
      - frontend
  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend
      args:
        - USER_DIRECTORY_API_BASE_URL=$USER_DIRECTORY_API_BASE_URL
    env_file: ./.env
    ports:
      - $REACT_LOCAL_PORT:$REACT_LOCAL_PORT
    environment:
      - REACT_LOCAL_PORT:$REACT_LOCAL_PORT
    networks:
      - frontend
volumes:
  db:
networks:
  backend:
  frontend:
